# Generated by Django 4.0.1 on 2022-02-16 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('user', '0003_remove_customuser_type_customuser_is_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='preparing_restaurants', to='orders.Dish'),
        ),
    ]
