# Generated by Django 4.0.1 on 2022-02-16 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_customuser_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='items',
            new_name='menu',
        ),
    ]
