# Generated by Django 4.0.1 on 2022-02-17 07:20

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_items_customuser_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.TextField(default='Example address here, with city, state and pincode'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
