# Generated by Django 4.0.1 on 2022-02-17 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_dish_picture_alter_order_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='picture',
        ),
    ]
